<?php
namespace app\index\controller;

use houdunwang\wechat\build\Base;
use houdunwang\wechat\WeChat;

class Wx extends Common{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        (new WeChat())->valid();
    }

    public function handle(){
        //消息管理模块
        $instance = ( new Base() )->instance( 'message' );
        //判断是否是文本消息
        if ( $instance->isTextMsg() ) {
            //获取消息内容
            $message = $instance->getMessage();
            //向用户回复消息
            $this->message->text( "jiwjfoi" );
        }
        //点击菜单事件
        if ($instance->isClickEvent())
        {
            //获取消息内容
            $message = $instance->getMessage();
            //向用户回复消息
            $this->message->text( "jiwjfoi" );
        }
        //当没有回复时交给默认消息处理
        $this->module( 'base' );
    }
}